server:
  port: 8081

spring:
  application:
    name: spring-rest-testing
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    #url: jdbc:oracle:thin:@localhost:1521:ORCLPDB1
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: EMPLOYEE
    password: dudkrish1A
    jpa:
      show-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          format_sql: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  sql:
    init:
      continue-on-error: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG